plugins:
  - jekyll-sitemap
  - jekyll-paginate

title: Code or not to code
email: vaclavelias@gmail.com
description: Blog about coding in .NET and C#.
baseurl: ""
#url: "https://mycutejekyllblog.com"
twitter_username: VasoElias
github_username:  VaclavElias
google_analytics: G-E0VDFZERRK
paginate: 10
paginate_path: "/blog/page:num"

#markdown: kramdown
#highlighter: rouge

#kramdown:
#    input: GFM 
#    syntax_highlighter: rouge

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
    - .vs
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/